### ISSUE TITLE
Neoreg 连接提示Base64 decode error

### ISSUE THREAD

**Issue by 0berry** [pen4uin/java-memshell-generator#19]
内存马类：org.apache.commons.lang.WebSocketUpgradeEidwInterceptor
注入器类：ch.qos.logback.xa.ReflectUtil

前面提示正常
[INFO    ]  [Ask NeoGeorg] Checking if NeoGeorg is ready
[INFO    ]  [Ask NeoGeorg] NeoGeorg says, 'All seems fine'

（更换key或者请求头，握手提示不对，说明注入是成功的）

代理流量时，返回包base64解码错误
[ERROR   ]  [HTTP] [NeoregReponseFormatError] Base64 decode error

**Comment by pen4uin** [comment]
可以提供更详细的信息吗，中间件，中间件版本，NeoGeorg客户端版本，方便我复现。

**Comment by Lengso** [comment]
目测 NeoGeorg客户端版本 版本不是最新的

**Comment by Lengso** [comment]
目前jmg用的neogeorg对应哪个版本呢？

**Comment by 0berry** [comment]
一开始我客户端用 NeoGeorg旧版本3.8.1，提示是key不对，换了NeoGeorg 5.2.0版本，就出现上面的情况了。

jMG v1.0.8

目标是jeecgboot应用（jeecgboot 3.4.4），fatJar形式的。启动是 java -jar  jeecg-system-start-3.4.4  
https://github.com/jeecgboot/jeecg-boot/tree/v3.4.4

**Comment by pen4uin** [comment]
> 一开始我客户端用 NeoGeorg旧版本3.8.1，提示是key不对，换了NeoGeorg 5.2.0版本，就出现上面的情况了。
> 
> jMG v1.0.8
> 
> 目标是jeecgboot应用（jeecgboot 3.4.4），fatJar形式的。启动是 java -jar jeecg-system-start-3.4.4 https://github.com/jeecgboot/jeecg-boot/tree/v3.4.4

使用 NeoGeorg  5.1.0 再试试（已更新 README），我这边测试没问题，可以正常工作

**Comment by pen4uin** [comment]
推荐使用 Listener，使用 Interceptor 需要去找到同时支持 GET 和 POST 的接口
