### ISSUE TITLE
对应版本列表

### ISSUE THREAD

**Issue by Lengso** [pen4uin/java-memshell-generator#20]
能给个版本列表吗，suo5、regeorg等更新过快
导致直接拿jmg生成打进去了但去对应的github上下载客户端连接不上

如：
Godzilla 4.0.1
suo 1.2.0

**Comment by pen4uin** [comment]
| 工具名称    | 测试版本（包括但不限于） |
| ----------- | ------------------------ |
| AntSword    | 2.1.15                   |
| Behinder    | 4.0.7                    |
| Godzilla    | 4.0.1                    |
| Neo-reGeorg | 5.1.0                    |
| Suo5        | 0.9.0                    |

**Comment by Lengso** [comment]
谢谢，建议加上
