### ISSUE TITLE
jmg-gui编译失败

### ISSUE THREAD

**Issue by jabadsssss** [pen4uin/java-memshell-generator#33]
老师请教一下，依赖项me.gv7.woodpecker:jexpr-encoder-utils:jar:0.2.2 不在中央仓库中，导致jmg-gui无法进行编译，该如何解决？
![1](https://github.com/user-attachments/assets/01f73fb7-7f10-4157-b2f6-82af2fbc0b6b)

**Comment by StevenLee003** [comment]
> 使用 Maven 的 `install:install-file` 命令将 JAR 文件手动安装到本地仓库。打开终端并运行以下命令：
> 
> mvn install:install-file -Dfile=E:\Environment\apache-maven-3.6.1\thrid-lib\jexpr-encoder-utils-0.2.2.jar -DgroupId=me.gv7.woodpecker -DartifactId=jexpr-encoder-utils -Dversion=0.2.2 -Dpackaging=jar

I've got the same problem. Through your comment, after I download and install the jexpr-encoder-utils from [https://github.com/woodpecker-appstore/jexpr-encoder-utils](https://github.com/woodpecker-appstore/jexpr-encoder-utils) by `mvn install:install-file -Dfile=/Users/user/Work/Tools/JMG/jexpr-encoder-utils-0.2.2.jar -DgroupId=me.gv7.woodpecker -DartifactId=jexpr-encoder-utils -Dversion=0.2.2 -Dpackaging=jar`, **It build succees**. Thanks very much.
