### ISSUE TITLE
可以增加下JBOSS的支持么

### ISSUE THREAD

**Issue by GitttttBottttt** [pen4uin/java-memshell-generator#5]
特别是老版本的JBOSS

**Comment by pen4uin** [comment]
Jboss 低版本套的是 tomcat，直接使用 tomcat 内存马即可，详见[Jboss 内存马](https://github.com/pen4uin/awesome-java-security/tree/main/middleware/jboss#%E5%86%85%E5%AD%98%E9%A9%AC)。
